name: tradukisto
description: Convert numbers to words (text representation).
version: 0.0.1
repository: https://github.com/solid-software/tradukisto

environment:
  sdk: ^3.4.3

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
